version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    container_name: jupyter
    volumes:
      - ./:/workspace
    command: >
      bash -c '
      pip install -e /workspace/.;
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
      '
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
